# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore

# Stage 2: Run
FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app
COPY --from=build /src .
ENTRYPOINT ["dotnet", "watch", "run", "--project", "Server/Server.csproj"]
